"""Abstract storage backend interface."""
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from bilinc.core.models import MemoryEntry
class StorageBackend(ABC):
    @abstractmethod
    async def init(self) -> None: ...
    @abstractmethod
    async def save(self, entry: MemoryEntry) -> bool: ...
    @abstractmethod
    async def load(self, key: str) -> Optional[MemoryEntry]: ...
    @abstractmethod
    async def delete(self, key: str) -> bool: ...
    @abstractmethod
    async def list_all(self) -> List[MemoryEntry]: ...
    @abstractmethod
    async def load_by_type(self, memory_type: Any, limit: int = 50) -> List[MemoryEntry]: ...
    @abstractmethod
    async def stats(self) -> Dict[str, Any]: ...
