"""Render public product documentation from the canonical JSON truth contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).parents[1]
MANIFEST = ROOT / "docs" / "public" / "product-truth.json"
OUTPUT = ROOT / "docs" / "public" / "product-truth.md"


def render(payload: dict[str, object]) -> str:
    package = payload["package"]
    cloud_mcp = payload["cloud_mcp"]
    urls = payload["public_urls"]
    benchmark = payload["benchmark_claims"]
    boundary = payload["boundary"]
    assert isinstance(package, dict)
    assert isinstance(cloud_mcp, dict)
    assert isinstance(urls, dict)
    assert isinstance(benchmark, dict)
    assert isinstance(boundary, dict)
    exports = ", ".join(f"`{item}`" for item in package["exports"])
    tools = ", ".join(f"`{item}`" for item in cloud_mcp["tools"])
    return f"""<!-- Generated by scripts/generate_public_truth_doc.py. Do not edit manually. -->
# Bilinc public product truth

- Package: `{package['name']}` `{package['version']}`
- Python: `{package['requires_python']}`
- License: `{package['license']}`
- Install: `{package['install']}`
- Canonical repository: {payload['canonical_repository']}
- Verified: `{payload['verified_at']}`

## Public surface

- SDK exports: {exports}
- Cloud MCP transport: `{cloud_mcp['transport']}`
- Cloud MCP tools: {tools}
- Documentation: {urls['documentation']}
- Signup: {urls['signup']}

## Boundary

{boundary['public_package']}

{boundary['not_shipped']}

## Benchmark policy

Current state: `{benchmark['state']}`. Numeric benchmark claims are public-approved: `{benchmark['public_approved']}`.

### {benchmark['label']}

- Scope: {benchmark['scope']}
- Legacy R@5: {benchmark['metrics']['legacy_r_at_5']}
- Legacy NDCG@5: {benchmark['metrics']['legacy_ndcg_at_5']}

{benchmark['qualification']}

{benchmark['rule']}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(json.loads(MANIFEST.read_text()))
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            print("Generated public truth document is stale. Run scripts/generate_public_truth_doc.py.", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
